feat: 사용자 플레이리스트 조회 구현
CommaProject/Comma-Back-end pull request #13
Opened 2023-04-12 07:03 UTC by given02

<h2>Jira Issue 번호</h2>

#52

<h2>작업 내용</h2>

- 사용자 플레이리스트 조회 구현

사용자 이메일로 플레이리스트 및 포함된 트랙을 조회

<h2>Check-List</h2>

- [x] PR 제목이 convention 에 맞는지 체크
- [x] PR Label 설정
- [x] Code Review 요청
- [x] Jira 리뷰 요청 상태로 변경

2023-04-12 12:52 UTC, 5tr1ker requested changes
TDD 파일 구분 필요 & DTO의 통일화

2023-04-12 14:06 UTC, given02 commented on src/main/java/com/team/comma/dto/PlaylistTrackResponse.java
> +}
모두 붙이려 했는데 일부 누락 되었습니다 수정할게요!

2023-04-12 14:06 UTC, given02 commented on src/main/java/com/team/comma/service/PlaylistService.java
> +            for(int i = 0; i < userPlaylist.size(); i++){
감사합니다 수정하겠습니다~!

2023-04-12 14:07 UTC, given02 commented on src/test/java/com/team/comma/repository/PlaylistRepositoryTest.java
> +}
특별한 이유는 없어서 따로 분리하도록 하겠습니다!

2023-04-12 16:25 UTC, 5tr1ker requested changes
TDD 는 더 분리할 수 있고 네이밍쪽에서 신경을 좀더 써주시면 될꺼같아요. 그리고 불변 클래스에 대해 더 이해가 필요할 꺼 같아요.

2023-04-12 16:25 UTC, 5tr1ker commented on src/main/java/com/team/comma/dto/PlaylistTrackResponse.java
>  }
불변 객체를 만족하지 못하는 코드라 생각합니다.

불변 클래스는 하단과 같이 따릅니다.

- 클래스는 final 로 선언합니다.
- 모든 클래스 변수를 private 와 final로 선언합니다.
- 객체를 생성하기 위해 생성자 또는 정적 팩토리 메서드를 추가합니다.
- 참조에 의해 변경가능성이 있는 경우 방어적 복사를 이용해 전달합니다.

2023-04-12 16:25 UTC, 5tr1ker commented on src/test/java/com/team/comma/repository/PlaylistTrackRepositoryTest.java
> +}
프로덕션 클래스 파일과 테스트 클래스 파일은 쌍으로 존재해야 하기에 PlaylistRepository 와 TrackRepository 를 더 분리해서 테스트 코드를 작성할 수 있을꺼같아요.

2023-04-12 16:25 UTC, 5tr1ker commented on src/test/java/com/team/comma/repository/PlaylistTrackRepositoryTest.java
> +        assertThat(result.size()).isEqualTo(0);
테스트 이름만 보고서 쉽게 이해할 수 있어야하는데 , 해당 이름보다 플레이리스트_곡_조회실패_데이터없음 
처럼 하는건 어떤가요?

2023-04-12 16:25 UTC, 5tr1ker commented on build.gradle
> +	implementation group: 'org.modelmapper', name: 'modelmapper', version: '2.3.8'
사용하지 않는 의존성은 제거해 주시는 게 좋을 꺼 같아요.

2023-04-13 05:24 UTC, given02 commented on src/test/java/com/team/comma/repository/PlaylistTrackRepositoryTest.java
> +        assertThat(result.size()).isEqualTo(0);
데이터가 없으면 빈리스트가 리턴되니까 실패라기보단 데이터 없음이 맞는거 같아서 그렇게 고칠게요

2023-04-13 07:32 UTC, given02 commented on src/main/java/com/team/comma/dto/PlaylistTrackResponse.java
>  }
불변 클래스에 대한 공부가 더 필요할 것 같습니다. 우선 참고하여 builder 대신 정적팩토리 메서드 추가했고 연관된 코드도 수정했습니다.

2023-04-13 13:53 UTC, wan2daaa commented on src/main/java/com/team/comma/entity/UserPlayList.java
> +    private String alarmStartTime;
나중에 엔티티를 수정할 거긴한데 LocalTime 으로 쓰구, 타입을 맞추는게 조금더 좋을것같아용!

2023-04-13 13:53 UTC, wan2daaa commented on src/test/java/com/team/comma/repository/MainRepositoryTest.java
> +                .userKey((long) 1234)
1234L 로 하면 타입캐스트 안해도됩니당

2023-04-13 13:58 UTC, wan2daaa commented on src/main/java/com/team/comma/entity/UserEntity.java
> +	private List<UserPlaylist> userPlaylist;
개인적으로 List나 컬렉션 타입일때 마지막에 컬렉션을 명시적으로 선언해주거나 , s 로 복수형태로 처리하는게 다른 곳에서 사용할때도 명확하게 이해하기 좋을것같아용

2023-04-13 14:24 UTC, wan2daaa requested changes
일단 코드 짜느라 고생했고 코드 가독성을 조금 생각하고 수정하면 좋을것같구 transactional도 한번 공부해보구 나머지는 상진이가 다 해준 것같아

2023-04-13 14:24 UTC, wan2daaa commented on src/main/java/com/team/comma/dto/PlaylistTrackResponse.java
>  }
@builder 와같은 롬복어노테이션은 우클릭후 refactor delombok 가능해서 어떵게 선언한지 확인가능합니다

2023-04-13 14:24 UTC, wan2daaa commented on src/main/java/com/team/comma/service/PlaylistService.java
> +@Transactional
@Transactional 의 명확한 개념에 대한 이해가 필요할 것같아요 그냥 클래스단위로 붙이면 메소드 마다 의미전달이 잘안돼용
https://techblog.woowahan.com/2668/

2023-04-13 14:24 UTC, wan2daaa commented on src/main/java/com/team/comma/service/PlaylistService.java
> +                if(playlistTracks.size() != 0) {
한번에 이해가 안되서 refactor 중 extractMethod로 분리하는게 좋을것같아용 어떤 코드인지 잘모르겠어용

2023-04-13 16:09 UTC, given02 commented on src/main/java/com/team/comma/entity/UserPlayList.java
> +    private String alarmStartTime;
UserPlayList는 현재 없는 클래스라서 이후 엔티티 수정된거에 대해서 반영해서 다시 PR 올리겠습니다~

2023-04-13 16:14 UTC, given02 commented on src/main/java/com/team/comma/service/PlaylistService.java
> +@Transactional
네 확인 하겠습니다~

2023-04-13 16:14 UTC, given02 commented on src/main/java/com/team/comma/service/PlaylistService.java
> +                if(playlistTracks.size() != 0) {
ㅠㅠ확인할게요

2023-04-13 16:33 UTC, given02 commented on src/main/java/com/team/comma/service/PlaylistService.java
> +                if(playlistTracks.size() != 0) {
수정완료!

2023-04-14 02:54 UTC, 5tr1ker approved these changes
👍 :)

2023-04-14 03:19 UTC, 5tr1ker requested changes
로직상 문제는 없지만 줄일 수 있는 코드가 있어보입니다.

2023-04-14 03:19 UTC, 5tr1ker commented on src/main/java/com/team/comma/dto/PlaylistResponse.java
> +}
list의 같은 경우 참조때문에 내부 객체가 변할 수 있습니다. 방어적 복사를 하는 코드가 누락되었습니다.
public List<String> getTracks() {
        return Collections.unmodifiableList(tracks);
}

2023-04-14 03:19 UTC, 5tr1ker commented on src/main/java/com/team/comma/dto/PlaylistResponse.java
> +        this.tracks = tracks;
객체 참조를 그대로 전달하기 보단 new List<>(tracks); 로 새로 만드는건 어떠신가요?

2023-04-14 03:19 UTC, 5tr1ker commented on src/main/java/com/team/comma/service/PlaylistService.java
> +        }
for Each문 쓸때 리스트가 비어있다면 실행하지 않습니다. 불필요한 if문을 제거해주세요.

2023-04-14 03:19 UTC, 5tr1ker commented on src/main/java/com/team/comma/service/PlaylistService.java
> +    }
이 코드는 바로 repository에서 조회하는게 좋을꺼같은데 이건 재완이형이랑 좀더 상의해볼게요.

2023-04-14 03:19 UTC, 5tr1ker commented on src/test/java/com/team/comma/controller/PlaylistControllerTest.java
> +}
200 요청을 받은 것과 동시에 데이터 3개가 잘 반환되었는지 확인하면 좋지 않을까요

2023-04-16 14:39 UTC, given02 commented
커밋 메세지 앞에 feat 까먹고 수정 못했어요 다음부터 정화하게 기입하겠습니다~

2023-04-20 11:32 UTC, 5tr1ker approved these changes

2023-04-20 11:32 UTC, wan2daaa approved these changes
코드 짜느라 고생했수 ㅎㅎ 잘했네

2023-04-20 11:33 UTC, 5tr1ker commented
고생하셨습니다! 시험때문에 지금 확인했어요

2023-04-20 15:50 UTC, merged