feat: Spotify Token 재발급 기능 구현
CommaProject/Comma-Back-end pull request #2
Opened 2023-04-02 12:40 UTC by 5tr1ker

<h2>Jira Issue 번호</h2>
<hr/>
#34

<h2>작업 내용</h2>
<hr/>
Spotify API 와 연동하여 사용자가 서비스를 요청할 때 Token이 올바르지 않거나 , 만료되었으면 API에 새로운 AccessToken을 요청하는 기능을 구현했습니다. 3600초 동안의 만료 시간이 있으며 Token이 만료되어도 서버에서 자동으로 재발급하기 때문에 프론트는 Token이 만료되었는지 신경을 쓰지 않아도 됩니다.

<h2>Check-List</h2>
<hr/>
 PR 제목이 convention 에 맞는지 체크
 PR Label 설정
 Code Review 요청
 Jira 리뷰 요청 상태로 변경

2023-04-02 12:54 UTC, given02 commented on src/main/java/com/team/comma/controller/SpotifyController.java
Backend convention에 맞게 requestmapping 대신 메소드에 맞는 어노테이션으로 수정

2023-04-02 12:57 UTC, given02 commented on src/main/java/com/team/comma/exception/GeneralExceptionHandler.java
예외처리에 대한 코드 및 메세지에 대해 API 명세서에 포함하여 작성

2023-04-02 13:07 UTC, given02 commented on src/main/java/com/team/comma/service/UserService.java
이건 스포티파이 아닌듯?

2023-04-02 13:14 UTC, given02 requested changes
SpotifyController 내 어노테이션 수정 필요

2023-04-04 13:13 UTC, given02 approved these changes
RequestMapping 어노테이션 수정 확인 완료 및 PR Approve

2023-04-04 13:50 UTC, ahhyunyoon approved these changes

2023-04-04 13:57 UTC, merged