feat : 백엔드 패키지 구조 수정 (계층형 -> 도메인형)
CommaProject/Comma-Back-end pull request #30
Opened 2023-04-27 12:18 UTC by wan2daaa

# Jira Issue 번호 
#75
# 작업내용
- [x] 계층형에서 도메인별로 변경 
# !!! 꼭 봐주세요!!!!
## 컨펌좀 부탁 드립니다 
- controller 패키지명을 presentation or controller 로 할지 의견 부탁드립니다!
- confused 패키지에 애매한 파일들을 빼놓았는데 어떻게 분리하면 좋을지 의견 부탁드립니다! (따로 패키지 만들어서 넣을지, 그냥 있는 도메인 패키지에 넣을지)
- test 에도 패키지 확인해 주셔야합니다! 
- 또 나누면 좋을 것 같은 패키지나 이건 왜 이렇게 합쳐놓았나 싶으신거 있으면 꼭 남겨주세요! 
- PR approved 말고 거절 해주세요!

# Check-List
- [x] PR 제목이 convention 에 맞는지 체크
- [x] PR Label 설정
- [x] Code Review 요청
- [x] Jira 리뷰 요청 상태로 변경

2023-04-27 15:23 UTC, given02 commented on src/test/java/com/team/comma/track/domain/TrackRepositoryTest.java
track/domain 패키지 안에 있는데 track패키지 안에 있어야 되는걸까요??

2023-04-27 15:31 UTC, given02 requested changes
잘 모르지만 컨펌 부탁한 내용 답변하자면... 
1. controller가 좋은 것 같습니다. 아니면 API 라고 하면 어떨까요?
2. 따로 패키지 만들어서 그 안에서 도메인별로 나누는게 좋을 것 같습니다.
3. 그 외엔 없네요. 프로젝트 구조가 직관적으로 드러나는 것 같아 좋은 것 같습니다
고생했어요 좀 더 화이팅!

2023-04-30 14:32 UTC, given02 approved these changes
변경 된 패키지 구조로 작업하고 restdocs 공부 하겠습니다~

2023-05-01 04:11 UTC, 5tr1ker approved these changes

2023-05-01 05:01 UTC, merged