feat: 플레이리스트 알람 설정 변경
CommaProject/Comma-Back-end pull request #31
Opened 2023-05-03 08:48 UTC by given02

<h2>Jira Issue 번호</h2>
#74

<h2>작업 내용</h2>
메인화면 플레이리스트 알람 설정 변경 기능 구현

<h2>Check-List</h2>

- [x] PR 제목이 convention 에 맞는지 체크
- [x] PR Label 설정
- [x] Code Review 요청
- [x] Jira 리뷰 요청 상태로 변경

2023-05-04 06:56 UTC, 5tr1ker requested changes

2023-05-04 06:56 UTC, 5tr1ker commented on gradle/wrapper/gradle-wrapper.properties
> +networkTimeout=10000
기본값이 30000인데 왜 10000 으로 설정하셨나요?

2023-05-04 06:56 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/playlist/dto/PlaylistRequest.java
> +}
래퍼 클래스를 사용하는 게 성능과 메모리를 더 잡아먹어서, 단순히 저장용도로 사용하려면 원시 타입을 사용하는게 더 나을꺼같아요.

2023-05-04 06:56 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/playlist/service/PlaylistService.java
> +        return createPlaylistResponse(playlists);
메서드명 잘못된거같아요.

2023-05-04 06:56 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/playlist/exception/PlaylistException.java
> +}
Exception 던지면 더이상 참조하지않나요?

2023-05-04 06:56 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/playlist/service/PlaylistService.java
> +
예외가 던져졌을 때 예외 처리가 잘 되나요? 아마 500 오류가 뜰꺼같아요

2023-05-04 09:34 UTC, wan2daaa commented on src/test/java/com/team/comma/spotify/track/repository/TrackRepositoryTest.java
> +        assertThat(result).isEmpty();
👍

2023-05-04 09:34 UTC, wan2daaa submitted a review, later dismissed
Exception 부분만 체크하고 상진이가 approved 하면 머지하면 될것같습니다 수고하셨습니당~

2023-05-04 13:40 UTC, given02 commented on gradle/wrapper/gradle-wrapper.properties
> +networkTimeout=10000
수정 한 적 없는데 왜 바껴있을까요...

2023-05-04 13:42 UTC, given02 commented on src/main/java/com/team/comma/spotify/playlist/service/PlaylistService.java
> +        return createPlaylistResponse(playlists);
메서명이 어떻게 잘 못 됐다는 건가요??

2023-05-05 05:54 UTC, 5tr1ker requested changes

2023-05-05 05:54 UTC, 5tr1ker commented on gradle/wrapper/gradle-wrapper.properties
> +networkTimeout=30000
원래 해당 코드를 작성하지 않으면 30000 으로 설정됩니다.

사용하지 않는 코드를 작성해서 혼란을 주는것보단 삭제하는게 나아보이네요

2023-05-05 05:54 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/playlist/service/PlaylistService.java
> +        }
수정하기 전 코드는 좋은 코드였지만 이런 코드도 나쁘지 않아요. 🤔
다만 제가 요청드린건 제가 만들어 놓은 ExceptionHandler 를 활용해서 세부적인 응답 코드를 설정하라는 의도였어요. 
변경에 실패했는데 200 OK 응답보단 400 응답이 더 맞는 거 같아서요.

2023-05-05 07:09 UTC, given02 commented on src/main/java/com/team/comma/spotify/playlist/service/PlaylistService.java
> +        }
아 예외처리가 안된다는 말이 사용자쪽에 예외 알림을 전달해야되는 걸로 이해 했네요. 이전 코드에서 응답 코드를 설정하는 걸로 다시 해볼게요!

2023-05-05 08:59 UTC, 5tr1ker requested changes

2023-05-05 08:59 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/playlist/controller/PlaylistController.java
>      }
HTTP API 명명 규칙에 위배됩니다.
자원의 행위를 URI 에 표현해서는 안됩니다.

2023-05-05 08:59 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/playlist/controller/PlaylistController.java
> +    }
사용자 이메일을 헤더로 받는 이유가 무엇인가요?

저희 시스템이 토큰 기반 인증 시스템이라 클라이언트에서는 이메일을 알 방법이 없습니다.
Cookie에 등록된 AccesssToken를 가져와 제가 작성한 JWT 클래스에서 UserEmail 를 추출하는 방법이 있습니다.

2023-05-05 08:59 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/playlist/dto/PlaylistTrackResponse.java
>      }
요기는 래퍼 클래스로 작성되어잇네요

2023-05-05 08:59 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/playlist/repository/PlaylistRepository.java
>  }
요기도 래퍼 클래스로 작성되어잇네요. 그리고 나중에 시간 되시면 JPQL을 QueryDSL 로 수정해보세요!

2023-05-05 08:59 UTC, 5tr1ker commented on src/main/java/com/team/comma/util/exception/handler/GeneralExceptionHandler.java
>  }
함수명이 예외를 발생시키는 메서드로 오해할 수 있습니다.

위의 다른 함수명 처럼 handle 을 붙이는건 어떤가요

2023-05-05 08:59 UTC, 5tr1ker commented on src/test/java/com/team/comma/spotify/playlist/repository/PlaylistTrackRepositoryTest.java
언더바 탐색 코드를 수정하신다 하시지 않았나욥

2023-05-05 11:29 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/playlist/controller/PlaylistController.java
>      }
update 면 PUT은 어떄요?

2023-05-05 14:04 UTC, 5tr1ker requested changes

2023-05-05 14:04 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/playlist/controller/PlaylistController.java
>      }
만약 일부를 수정한다면 PUT 을 사용해주세요.

2023-05-05 14:40 UTC, 5tr1ker approved these changes

2023-05-05 14:46 UTC, wan2daaa approved these changes
수정하느라 고생했어~

2023-05-05 14:48 UTC, merged