refactor: track service 추가 및 playlist service 코드 수정
CommaProject/Comma-Back-end pull request #35
Opened 2023-05-05 15:28 UTC by given02

<h2>Jira Issue 번호</h2>
#63

<h2>작업 내용</h2>
- playlist service 코드 일부 track service에 추가

<h2>Check-List</h2>

- [x] PR 제목이 convention 에 맞는지 체크
- [x] PR Label 설정
- [x] Code Review 요청
- [x] Jira 리뷰 요청 상태로 변경

2023-05-07 06:29 UTC, 5tr1ker requested changes

2023-05-07 06:29 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/playlist/service/PlaylistService.java
> +            TrackService trackService = new TrackService();
빈 주입 이거 맞나요?

2023-05-07 06:34 UTC, 5tr1ker requested changes

2023-05-07 06:34 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/playlist/service/PlaylistService.java
> +            List<PlaylistTrackArtistResponse> artistList = trackService.createArtistResponse(playlistTrack.getTrack().getTrackArtistList()); // track의 artist list
주석을 달아서 설명하지 말고 메서드 이름으로 표현할 수 있게 해주세요.

2023-05-07 06:34 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/track/service/TrackService.java
> +    public List<PlaylistTrackArtistResponse> createArtistResponse(List<TrackArtist> artistList){
메서드명은 가수 응답을 만드는 거라고 표현하고 있는데, 실제 비즈니스 모델은 플레이리스트에서 트랙의 가수를 추출합니다. 메서드 명만 보고도 알 수 있어야 하는데 코드도 봐야하면 나중에 확장할 때 힘들어요.

 메서드 명만 보고도 역할을 알 수 있게 명시적으로 이름을 붙여주세요

2023-05-07 11:17 UTC, given02 commented on src/main/java/com/team/comma/spotify/track/service/TrackService.java
> +    public List<PlaylistTrackArtistResponse> createArtistResponse(List<TrackArtist> artistList){
트랙의 가수를 추출해서 response list를 만들고 있어요. 메서드 명이 길어져서 나름 요약해서 만들었는데 최대한 수정해볼게요

2023-05-07 11:19 UTC, given02 commented on src/main/java/com/team/comma/spotify/playlist/service/PlaylistService.java
> +            TrackService trackService = new TrackService();
쏘리ㅠ

2023-05-07 11:56 UTC, given02 commented
언급한 메서드명은 이해하기 쉽게 지어보도록 고민해볼게요 우선 수정된 내용 확인 후 리뷰해주시면 감사하겠습니다.

2023-05-07 11:58 UTC, given02 commented on src/main/java/com/team/comma/spotify/playlist/service/PlaylistService.java
> +            List<PlaylistTrackArtistResponse> artistList = trackService.createArtistResponse(playlistTrack.getTrack().getTrackArtistList()); // track의 artist list
너무 어려워요...

2023-05-08 04:12 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/playlist/service/PlaylistService.java
>      public List<PlaylistResponse> getPlaylist(final String accessToken) {
getPlaylists 는 어때용 하나의 플레이리스트를 리턴하는 것같아용

2023-05-08 04:14 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/playlist/service/PlaylistService.java
> +    public List<PlaylistResponse> getPlaylist(String accessToken) {
final 쓰는거 좋은것같은데 왜 뺀건가용?

2023-05-08 04:15 UTC, wan2daaa commented on src/test/java/com/team/comma/spotify/playlist/service/PlaylistServiceTest.java
> +                getPlaylist()
👍

2023-05-08 04:17 UTC, wan2daaa commented on src/test/java/com/team/comma/spotify/playlist/service/PlaylistServiceTest.java
> +    public Playlist getPlaylist() {
이렇게 만든건 좋은데 다음 사람이 코드를 작성할때 재활용하기 좋지 않아서 인자를 alarmFlag나 TrackPlaylist를 외부에서 주입하게 해주는 것도 좋을 것같아요 
 예를 들어서 `getPlaylistWithAlarmFlag(boolean alarmFlag, List<PlaylistTrack> playlistTrackList)`

2023-05-08 05:24 UTC, given02 commented on src/main/java/com/team/comma/spotify/playlist/service/PlaylistService.java
> +    public List<PlaylistResponse> getPlaylist(String accessToken) {
service 내 다른 메서드에서는 사용을 안해서 통일하려고 뺐는데 지금보니 모두 적용할 수 있을 것 같아서 추가 할게요!

2023-05-08 05:33 UTC, given02 commented on src/test/java/com/team/comma/spotify/playlist/service/PlaylistServiceTest.java
> +    public Playlist getPlaylist() {
다른 entity 요소들도 고려하다가 그냥 최소한으로만 만들자 했었는데 alarm이란 list 받을 수 있게 하는 정도만 해도 좋을 것 같네요

2023-05-09 08:09 UTC, 5tr1ker approved these changes

2023-05-11 04:16 UTC, wan2daaa approved these changes
수정하느라 고생하셨어용! 👍

2023-05-11 05:08 UTC, merged