feat: 메인 세팅 API 구현
CommaProject/Comma-Back-end pull request #36
Opened 2023-05-07 13:44 UTC by wan2daaa

<h2>Jira Issue 번호</h2>
60

<h2>작업 내용</h2>

- 메인 세팅 API 구현 
- ENUM 타입으로 상수 핸들링 예시 추가

<h2>Check-List</h2>

- [x] PR 제목이 convention 에 맞는지 체크
- [x] PR Label 설정
- [x] Code Review 요청
- [x] Jira 리뷰 요청 상태로 변경

2023-05-08 05:58 UTC, given02 approved these changes
메서드명, 테스트명이 자세하니까 좋은 것 같네요. 어려웠던 부분인데 많이 배웠습니다!

2023-05-08 06:00 UTC, given02 commented on src/main/java/com/team/comma/spotify/playlist/controller/PlaylistTrackController.java
> +    public ResponseEntity<MessageResponse> disconnectPlaylistAndTrack
removePlaylistTrack은 어떨까해서 남겨봅니다,,,

2023-05-08 12:51 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/playlist/controller/PlaylistTrackController.java
> +    public ResponseEntity<MessageResponse> disconnectPlaylistAndTrack
좋은것같아용!

2023-05-09 08:05 UTC, 5tr1ker requested changes
추후에 컨벤션을 더 정해서 코드를 일체화 하는 방향으로 가면 좋을 꺼 같아요.

2023-05-09 08:14 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/playlist/controller/PlaylistController.java
> +    @GetMapping("/userPlaylist")
단수형인줄알았는데 공부 다시해야겠네요 감사합니다 :> 👍

2023-05-09 08:15 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/history/repository/HistoryRepositoryCustom.java
> +
상진이 queryDSL 훔쳐보다가 걸렸네요,, 수정하겠습니다 :< 👍

2023-05-09 08:16 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/playlist/controller/PlaylistTrackController.java
> +}
이게 준영님이랑 코드가 겹쳐서 코드를 일단 머지 후에 다시 리팩토링하면 좋을것같아요! :> 👍

2023-05-09 08:17 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/playlist/controller/PlaylistTrackController.java
> + */
ㅋㅋㅋㅋㅋㅋ 💯

2023-05-09 08:18 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/playlist/domain/Playlist.java
>      private Boolean alarmFlag;
그럼 엔티티도 원시형으로 처리하는게 낫나요? 좋습니다.. 
확인했습니다! 수정하겟습니다 :> 👍

2023-05-09 08:20 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/playlist/domain/Playlist.java
> +
좋아요 그럼 new ArrayList로 초기화 시키는게 깔끔할것같아용 ㅎ

2023-05-09 08:20 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/playlist/repository/PlaylistRepository.java
> +
꼭 하겠습니다! 🥇 :>

2023-05-09 08:21 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/playlist/service/PlaylistService.java
> +                playlistTrack.getTrack().getTrackArtistList()); // track의 artist list
넵 쓸데없는 주석 .. - 클린코드

2023-05-09 08:22 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/playlist/service/PlaylistService.java
> +        );
enum자체를 받는게 훨씬 좋네요! 최곱니다 ㅎㅎ 💯

2023-05-09 08:22 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/search/service/SpotifyService.java
> +}
Spotify-> Search로 변경하도록하겠습니다.

2023-05-12 14:15 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/playlist/domain/Playlist.java
>      private Boolean alarmFlag;
원시형으로 적용시 builder 패턴 적용이안되서 그대로 일단 유지하고 좋은 방법 찾아보는 걸로 하면 좋을 것 같습니다!

2023-05-14 10:40 UTC, 5tr1ker approved these changes

2023-05-14 12:10 UTC, given02 approved these changes

2023-05-14 12:14 UTC, merged