feat: Spotify 추천 API 개발 및 S3 스토리지 연동
CommaProject/Comma-Back-end pull request #37
Opened 2023-05-07 14:06 UTC by 5tr1ker

Spotify 추천 API 개발 및 S3 스토리지 연동

2023-05-08 03:26 UTC, given02 commented on src/main/java/com/team/comma/user/repository/UserRepositoryImpl.java
user name과 nickname으로 user 정보를 조회하는 이유가 있을까요?? findByEmail도 재정의한 이유가 궁금합니다

2023-05-08 03:29 UTC, given02 approved these changes
저도 QueryDsl 적용 해볼게요 수고했어요~

2023-05-08 04:20 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/search/service/SearchService.java
>          return MessageResponse.of(REQUEST_SUCCESS , "요청이 성공적으로 수행되었습니다." , result);
이런 부분은 
`REQUEST_SUCCESS(1, "요청이 성공적으로 수행되었습니다.");`
enum으로 공통으로 한번 리팩토링 하는건 어떨까용 ㅎ

2023-05-08 04:23 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/search/service/SearchService.java
> +        if(executeResult instanceof SpotifyApi) {
이 부분 혹시 명시적 변환 해버리면 안될까요?
`SpotifyApi executeResult = (SpotifyApi) spotifySearchCommand.executeCommand(recommend);`

2023-05-08 04:54 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/search/service/SearchService.java
> +        if(genreList.isEmpty()) {
Optional로 처리하는건 어떨까요?

2023-05-08 05:06 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/search/service/SearchService.java
> +        for(int i = 0; i < 4 ; i++) {
이게 무슨 역할을 하는지 잘 몰라서 메서드로 빼주면 좋을것같아용 ㅎ

2023-05-08 05:07 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/search/service/SearchService.java
> +            throw new SpotifyException("사용자 관심 아티스트를 찾을 수 없습니다.");
여기도 Optional로 처리할 수 있으면 하는게 좋을 것같아요!

2023-05-08 05:21 UTC, wan2daaa commented on src/main/java/com/team/comma/user/service/UserService.java
> +        if (user == null) {
이런부분도 나중에 시간나면 리팩토링 하는것도 좋을것같아요 :>

2023-05-08 05:23 UTC, wan2daaa commented on src/test/java/com/team/comma/spotify/search/controller/SearchControllerTest.java
> +        doThrow(new AccountException("사용자를 찾을 수 없습니다.")).when(spotifyService).searchRecommendation(any(String.class));
이건 그냥 참고로 `anyString()` 도 있어용 :>

2023-05-08 05:24 UTC, wan2daaa commented on src/test/java/com/team/comma/spotify/search/controller/SearchControllerTest.java
> +                MockMvcRequestBuilders.get(api).contentType(MediaType.APPLICATION_JSON)
MeidaType도 static Import 해버려도 상관없을것같아용 ㅎ

2023-05-08 05:25 UTC, wan2daaa commented on src/test/java/com/team/comma/spotify/search/controller/SearchControllerTest.java
> +        doThrow(new SpotifyException("사용자 관심 아티스트를 찾을 수 없습니다.")).when(spotifyService).searchRecommendation(any(String.class));
개인적으로 doThrow 하고 `.when`에서 엔터로 띄우는게 더 가독성이 좋을것같지않나용 ? :>

2023-05-08 05:28 UTC, wan2daaa commented on src/test/java/com/team/comma/user/repository/FavoriteArtistRepositoryTest.java
> +        List<String> result = queryFactory.select(favoriteArtist.artistName)
queryDsl은 이렇게 직접 작성해서 테스트 해야하나욤? 
메소드로는 못가져오나용?

2023-05-08 05:30 UTC, wan2daaa commented on src/docs/asciidoc/spotifySearch.adoc
> +include::{snippets}/spotify/recommend/notFountFavoriteArtist/http-request.adoc[]
개인적으로 성공 API가 있는데 실패 Request 내용이 필요할까요? 저는 일단 Response에 대한 부분만 작성했는데 의견이 궁금합니다 ! :>

2023-05-08 05:32 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/search/service/SearchService.java
> +        String favoriteGenre = getRandomFourFavoriteGenreByUser(accessToken);
개인적으로 
`getFourRandomFavoriteGenreByUser` 가 나을것같아요! 
그냥 순서대로 읽었을때 네개의 랜덤favorite장르 이런식으로 읽혀서 더 잘읽힐것같아요!

2023-05-08 05:35 UTC, wan2daaa commented on src/test/java/com/team/comma/spotify/search/controller/SearchControllerTest.java
> +        Image image1 = new Image.Builder().setHeight(640).setWidth(640).setUrl("https://i.scdn.co/image/ab67616d0000b2737645cbd0f9fefff1771ea50c").build();
이미지 크기를 상수로 뺄까용?

2023-05-08 05:39 UTC, wan2daaa requested changes
또 S3연동하고 어려운 추천 쪽 개발하시느라 고생하셨습니다! 
그 네이밍이나 Optional 처리 부분한번만 검토해주시면 될 것같아요 !수고하셨습니다 
:> 👍

2023-05-10 08:26 UTC, wan2daaa approved these changes
Optional로 다 고친다고 고생하셨습니당 ㅎ 아주 지대로 공부했겠네요 :> 👍

2023-05-10 12:21 UTC, given02 submitted a review, later dismissed
바뀐 코드 모두 확인했어요 이번에도 고생 많았습니다!

2023-05-11 05:27 UTC, given02 approved these changes

2023-05-12 04:31 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/history/controller/HistoryController.java
> +    @GetMapping("/historys")
이고... histories 아니에용 ?? ㅠ

2023-05-12 04:33 UTC, wan2daaa submitted a review, later dismissed
훨씬더 깔끔한것 같아용 ㅎ 수고하셨어요 굿굿

2023-05-12 05:17 UTC, wan2daaa approved these changes

2023-05-12 05:44 UTC, given02 approved these changes

2023-05-12 05:47 UTC, merged