feat: Archive 등록 및 아티스트, 팔로우 기능 구현
CommaProject/Comma-Back-end pull request #38
Opened 2023-05-15 06:38 UTC by 5tr1ker

<h2>Jira Issue 번호</h2>

<h2>작업 내용</h2>

- Archive 등록 API 개발
- FavoriteArtist 등록 , 삭제 API 구현
- Follow 기능 구현 ( 등록 , 차단 , 차단해제 )

<h2>Check-List</h2>

- [x] PR 제목이 convention 에 맞는지 체크
- [x] PR Label 설정
- [x] Code Review 요청
- [x] Jira 리뷰 요청 상태로 변경

2023-05-15 12:43 UTC, given02 approved these changes
모두 확인 했습니다! 고생 했어요~

2023-05-15 13:25 UTC, wan2daaa commented on src/main/java/com/team/comma/follow/controller/FollowingController.java
> +        return ResponseEntity.status(HttpStatus.CREATED)
저도 이렇게 status 지정해봐야겠네요 디테일 최고시다,,

2023-05-15 13:27 UTC, wan2daaa commented on src/main/java/com/team/comma/follow/dto/FollowingRequest.java
> +@NoArgsConstructor
기본생성자 private으로 막는게 좋을것같아요 ! :>

2023-05-15 13:28 UTC, wan2daaa commented on src/main/java/com/team/comma/follow/repository/FollowingRepositoryImpl.java
> +    QUser user1 = new QUser("user1");
이렇게 쓸수있군요,, 참고하겠습니다 감사합니다 ! :> 👍

2023-05-15 13:29 UTC, wan2daaa commented on src/main/java/com/team/comma/follow/repository/FollowingRepositoryImpl.java
> +                        JPAExpressions.select(following.id).from(following)
내부쿼리는 JPAExpressions 를 사용해서 작성하는건가용?

2023-05-15 13:33 UTC, wan2daaa commented on src/main/java/com/team/comma/follow/service/FollowingService.java
> +        if(isFollowed(toUserEmail , fromUserEmail)) {
👍

2023-05-15 13:36 UTC, wan2daaa commented on src/main/java/com/team/comma/follow/service/FollowingService.java
> +        User userFrom = userRepository.findByEmail(fromUserEmail)
음 이부분을 
`User userTo = userRepository.findByEmail(toUserEmail)
                .orElseThrow(AccountException::new);
`
로 하고 RestControllerAdvice에 공통으로 처리하는건 어떤가용?

2023-05-15 13:39 UTC, wan2daaa commented on src/test/java/com/team/comma/follow/repository/FollowingRepositoryTest.java
> +        User toUser = User.builder()
이거 저 해보니까 QueryDsl 따로 구현안하고 repository에 들고와도 정상적으로 실행되는것 같은데 한번 확인해보실래요? :>

2023-05-15 13:44 UTC, wan2daaa commented on src/test/java/com/team/comma/follow/service/FollowingServiceTest.java
> +        Throwable thrown = catchThrowable(() -> followingService.addFollow("token" , "toUserEmail"));
저는 when,then 합쳐서 테스트 했는데 참고해보겠습니다 ! :>

2023-05-15 13:47 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/archive/dto/ArchiveRequest.java
> +@NoArgsConstructor
이부분도 private ,, :>

2023-05-15 13:50 UTC, wan2daaa commented on src/test/java/com/team/comma/spotify/archive/controller/ArchiveControllerTest.java
> +                        .contentType(MediaType.APPLICATION_JSON).cookie(new Cookie("accessToken" , "token")));
저는 개인적으로 이쪽 부분은 content , content ,type, cookie 모두 줄바꿈하는게 좋다고 생각해요 코드를 읽을 때 명확하게 알 수 있을 것같구, `MockMvcRequestBuilders ` static임포트해서 이게 post인게 조금더 눈에 잘띄게 할 수 있을 것같아요 ㅎ

2023-05-15 13:51 UTC, wan2daaa commented on src/test/java/com/team/comma/spotify/archive/controller/ArchiveControllerTest.java
> +        final MessageResponse result = gson.fromJson(
왜 검증을 혹시 두번하는건가용? restdocs에서 검증해주지 않나용? 
data 가 null이면, .ignore 처리하는건 별로일까용?

2023-05-15 13:53 UTC, wan2daaa commented on src/test/java/com/team/comma/spotify/archive/service/ArchiveServiceTest.java
> +        assertThat(thrown).isInstanceOf(AccountException.class).hasMessage("사용자를 찾을 수 없습니다.");
💯

2023-05-15 13:58 UTC, wan2daaa requested changes
또 엄청난 양을 작업하시고,, 고생하셨습니다 
코드가 항상 일정한 패턴으로 작성하셔서 읽기 좋고 이해하기 좋은것같아요!
작지만 제 수정사항 한번만 체크해주시면 될것같아요 수고하셨습니다 :> 👍

2023-05-16 14:07 UTC, 5tr1ker commented on src/main/java/com/team/comma/follow/repository/FollowingRepositoryImpl.java
> +                        JPAExpressions.select(following.id).from(following)
넹!

2023-05-16 14:08 UTC, 5tr1ker commented on src/main/java/com/team/comma/follow/service/FollowingService.java
> +        User userFrom = userRepository.findByEmail(fromUserEmail)
그렇기엔 다른 예외 상황이 있어서 나중에 리팩토링할 때 NotFoundAccount 로 빼서 바꿔보겠습니다.

2023-05-16 14:12 UTC, 5tr1ker commented on src/test/java/com/team/comma/spotify/archive/controller/ArchiveControllerTest.java
> +        final MessageResponse result = gson.fromJson(
restDocs 에서는 검증을 하지 않고 단순히 타입과 값을 가지고 문서를 만들어주는 라이브러리여서 , 검증은 따로 해주어야해요!

그리고 프론트에서 code , message , data 3가지로 응답받게 설정해놓아서 null 이여도 보내줘야 할 꺼 같아요.

2023-05-16 14:13 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/favorite/artist/repository/FavoriteArtistRepositoryCustom.java
> +    Optional<FavoriteArtist> findFavoriteArtistByUser(User user , String artistName);
유저가 해당 아티스트를 가지고 있는지 확인하려고 만든 메서드라 , 추후 확장성을 위해 저렇게 개발해 놓았습니다!

2023-05-16 14:20 UTC, wan2daaa submitted a review, later dismissed
고생하셨습니당 ㅎ 👍

2023-05-18 14:44 UTC, wan2daaa approved these changes
가독성이 훨씬 좋아진것같아요! 고생하셨습니다 :>

2023-05-21 03:46 UTC, given02 approved these changes
수고 많았어요~!

2023-05-21 04:24 UTC, merged