feat: Player API 구현 및 Track 알림 API 구현
CommaProject/Comma-Back-end pull request #39
Opened 2023-05-15 17:07 UTC by wan2daaa

<h2>Jira Issue 번호</h2>
79

<h2>작업 내용</h2>

- Player 트랙 재생 및 정지 API 구현
- TrackId로 트랙의 AlarmFlag 변경 API 구현

<h2>Check-List</h2>

- [x] PR 제목이 convention 에 맞는지 체크
- [x] PR Label 설정
- [x] Code Review 요청
- [x] Jira 리뷰 요청 상태로 변경

2023-05-16 02:12 UTC, given02 approved these changes
코드 모두 확인했습니다! 고생했어요~

2023-05-16 15:15 UTC, 5tr1ker requested changes
URI 명하구 제가 만들어 놓은 라이브러리를 활용해주시면 좋을 꺼 같아요!

2023-05-16 15:15 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/player/service/PlayerService.java
> +    }
execute 로 실행시키는 함수 역시 SpotifySearchCommand 에 포함되어 있습니다.

2023-05-16 15:15 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/player/service/PlayerService.java
> +    }
Spotify API에서는 토큰이 만료되었을 때 UnauthorizedException 를 띄우면서 요청을 처리하지 않는데 해당 예외처리에 대한 부분이 없습니다.

로직은 SpotifySearchService 클래스를 참고해주세요.

2023-05-16 15:15 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/player/service/PlayerService.java
> +
근데 재생 같은 부분은 백엔드에서 클라이언트로 전달할 수 없지 않나요?

제가 기억하기론 예전 회의 때 spotify 트랙 ID 만 넘겨주면 프론트엔드에서 플레이어를 구현하는걸루 알고있어요..

2023-05-16 15:15 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/playlist/repository/PlaylistTrackRepository.java
> +
여기두 QueryDSL 로 통일해서 작성하면 좋을꺼같아요!

2023-05-16 15:15 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/track/controller/TrackController.java
> +}
여기 URI두 복수 명사로 해주시면 좋을 꺼 같아요..!

2023-05-18 14:51 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/player/controller/PlayerController.java
> +        );
좋습니다 일단 명사형 단어는 전부 복수형으로 진행하겠습니다 ! 
하지만 예외적으로 start 나 pause 는 어떻게 보면 행동을 의미하기 때문에 그대로 단수형으로 진행하겠습니다 ! :>

2023-05-21 14:17 UTC, given02 approved these changes
고생 하셨습니다~!

2023-05-22 02:27 UTC, 5tr1ker requested changes

2023-05-22 02:27 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/player/service/PlayerService.java
> +        return MessageResponse.of(REQUEST_SUCCESS, PlayerResponseDto.of(accessToken, uri));
다른 DTO 파일처럼 뒤에 Dto 이름을 빼는건 어떤가요.

2023-05-22 02:27 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/player/controller/PlayerController.java
> +    }
HTTP API 규칙 상 URI의 명사형 , 동사형에 따라 단수,복수를 구분하지 않습니다. 
보통 문법적으로 맞지 않아도 모든 인스턴스를 복수형으로 처리하는 거 같아요.

2023-05-22 02:27 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/player/controller/PlayerController.java
> +    }
그리고 해당 API는 단순히 트랙과 Token만 반환하는데 Track Controller 에 합치는건 어떤가요
Player 이름은 거리가 좀 멀어보여요.

2023-05-22 02:27 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/track/controller/TrackController.java
> +}
여기는 수정이 안되어있습니다.

2023-05-22 02:28 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/player/service/PlayerService.java
> +        return MessageResponse.of(REQUEST_SUCCESS, PlayerResponseDto.of(accessToken, uri));
좋은생각입니다!

2023-05-22 02:29 UTC, wan2daaa commented on src/main/java/com/team/comma/spotify/player/controller/PlayerController.java
> +    }
그것도 좋은 생각인것같습니다 근데 그럼 docs 에서 볼때 조금 헷갈릴것 같다는 생각이 드는데 어떻게 생각하시나욤??

2023-08-07 08:33 UTC, given02 commented
리팩토링 후 제가 다시 pr 올리는 것으로 하겠습니다.

2023-08-10 06:41 UTC, closed without merging