refactor: 플레이리스트 삭제 기능 구현 오류 수정
CommaProject/Comma-Back-end pull request #41
Opened 2023-05-21 14:11 UTC by given02

<h2>Jira Issue 번호</h2>
72

<h2>작업 내용</h2>

- 플레이리스트 삭제 기능 구현
- playlist service 및 track service 내 작업 완료 되었던 코드가 사라져서 다시 추가
- 코드 충돌 해결이 안돼서 다시 PR

<h2>Check-List</h2>

- [x] PR 제목이 convention 에 맞는지 체크
- [x] PR Label 설정
- [x] Code Review 요청
- [x] Jira 리뷰 요청 상태로 변경

2023-05-22 02:42 UTC, 5tr1ker requested changes

2023-05-22 02:42 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/playlist/controller/PlaylistController.java
>      }
해당 API의 HTTP API는 자체 설명 구조를 전혀 띄지 못하고 있습니다.

2023-05-22 02:42 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/playlist/controller/PlaylistController.java
> +        );
메서드에 patch 는 적절하지 않은거 같아요. 다른 클래스처럼 modify 로 통일해야할 꺼 같아요.

2023-05-22 02:42 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/playlist/controller/PlaylistController.java
> +                .body(playlistService.updatePlaylistsDelFlag(playlistIdList));
URI에 행위가 들어가면 안됩니다...

2023-05-22 02:42 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/playlist/repository/PlaylistRepositoryCustom.java
> +    long deletePlaylist(@Param("id") long id);
QueryDSL 에 @Param 이 사용되나요?

2023-05-22 02:42 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/playlist/service/PlaylistService.java
> +        }
서버 시점에서 클라이언트를 신경쓰지 않아도 됩니다. 단순히 오류 이름만 알려주면됩니다. 뒤에 " 다시 시도해 주세요." 는 제거해주세요.

2023-05-25 02:59 UTC, 5tr1ker approved these changes

2023-05-30 00:11 UTC, wan2daaa approved these changes
코드 깔끔하게 잘된것같네요 고생하셨습니다!

2023-05-30 03:01 UTC, merged