feature: 플레이리스트 트랙 추가 기능 구현(기존 플레이리스트 저장 기능에서 수정)
CommaProject/Comma-Back-end pull request #42
Opened 2023-05-30 12:39 UTC by given02

<h2>Jira Issue 번호</h2>

81

<h2>작업 내용</h2>

- 플레이리스트 트랙 추가 기능 구현
- playlistTrackSaveRequestDto에 playlistIdList와 trackRequestList에 트랙 정보를 추가로 받아옴
- playlistIdList가 비어있으면 신규 생성 그렇지 않으면 기존 플레이리스트에 트랙 추가
- 신규 생성 혹은 기존 플리에 트랙 추가 모두 트랙이 존재하는 지 먼저 확인 후 없으면 트랙 저장 후 플리에 추가

<h2>기타</h2>

- 깃허브 잔디가 안 심어져서 이것저것 해보다가 커밋 기록이 지저분해서 브랜치를 새로 만듬
- 지금도 지저분한 기록이 좀 있는데 양해 바랍니다...

<h2>Check-List</h2>

- [x] PR 제목이 convention 에 맞는지 체크
- [x] PR Label 설정
- [x] Code Review 요청
- [x] Jira 리뷰 요청 상태로 변경

2023-05-30 15:46 UTC, 5tr1ker requested changes

2023-05-30 15:46 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/playlist/service/PlaylistTrackService.java
> +        if (dto.getPlaylistIdList() == null){
if (dto.getPlaylistIdList() == null){  말고
if (dto.getPlaylistIdList().isEmpty){ 로 수정합시다.

2023-05-31 05:23 UTC, given02 commented on src/main/java/com/team/comma/spotify/playlist/service/PlaylistTrackService.java
> +        if (dto.getPlaylistIdList() == null){
원래 isEmpty 사용했었는데 nullpointerexception 발생해서 수정했어요. 우선 다시 수정하고 빈 배열 받는걸로 수정할게요.

2023-06-03 06:23 UTC, wan2daaa approved these changes

2023-06-03 13:27 UTC, merged