feature: 추천 정보 상세 조회 기능 구현 및 추천 리스트 조회 기능 수정
CommaProject/Comma-Back-end pull request #77
Opened 2023-08-01 08:13 UTC by given02

<h2>Jira Issue 번호</h2>

93

<h2>작업 내용</h2>

- 추천 정보 상세 조회 기능 구현
- 추천 받은 리스트 조회 기능 -> 추천 리스트 조회 기능 으로 수정
- 추천 리스트 조회 시 보낸 리스트/ 받은 리스트 로 구분하여 요청

<h2>Check-List</h2>

- [x] PR 제목이 convention 에 맞는지 체크
- [x] PR Label 설정
- [x] Code Review 요청
- [x] Jira 리뷰 요청 상태로 변경

2023-08-01 12:34 UTC, 5tr1ker requested changes

2023-08-01 12:34 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/recommend/repository/RecommendRepositoryImpl.java
>      }
이쪽에 toUser 와 fromUser 은 Lazy 인데 , 조인 없이 가져오면 예외가 발생하지않나요?
그리고 필드를 가져오기 위해 복잡도가 좀 심한거같아요.

2023-08-01 12:34 UTC, 5tr1ker commented on src/test/java/com/team/comma/spotify/recommend/repository/RecommendRepositoryTest.java
> +
여기에 toUser와 fromUser가 프록시 객체가 아닌지 확인하는 코드도 필요할 꺼 같아요.
Lazy 객체라 아마 오류가 뜰꺼같아요

2023-08-01 12:34 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/recommend/dto/RecommendResponse.java
> +        this.comment = recommend.getComment();
여기 상당히 복잡해보이는데 하단에 Lazy 문제가 해결되면 한번 확인해주세요. 
toUser 와 fromUser 조인하시면 따로 데이터를 가져올텐데 그걸 활용하면 될꺼같아요

2023-08-01 12:34 UTC, 5tr1ker commented on src/main/java/com/team/comma/spotify/recommend/repository/RecommendRepositoryImpl.java
> +
여기도 한번 테스트 코드랑 Lazy 객체좀 확인해주세요

2023-08-01 13:13 UTC, given02 commented on src/main/java/com/team/comma/follow/controller/FollowingController.java
>      public ResponseEntity<MessageResponse> getFollowingList(@CookieValue String accessToken) throws AccountException {
이거는 위에 isFollow랑 중복이어서 필요 할 것 같은데 다시 확인 부탁해요!

2023-08-02 03:48 UTC, given02 commented on src/main/java/com/team/comma/spotify/recommend/repository/RecommendRepositoryImpl.java
>      }
우선 조인은 빼먹은게 맞네요 복잡도는 해결 해볼게요!

2023-08-03 02:50 UTC, 5tr1ker approved these changes

2023-08-04 08:09 UTC, merged