feature: 프로젝트 리팩토링
CommaProject/Comma-Back-end pull request #8
Opened 2023-04-07 08:23 UTC by wan2daaa

# Jira Issue 번호 
#62
# 작업내용
- war-> jar 로 변경 
- 패키지 구조 변경
- 엔티티 명 수정 
- 오탈자 수정 (Swagger에서 /register 부분 recommendTime 예시 안나오는 오류 수정 완료)

2023-04-07 08:45 UTC, 5tr1ker requested changes
Config를 또 생성하지 않고 Security 에서 cors 오류를 해결할 수 있는 방법이 있을 것 같습니다.
https://toycoms.tistory.com/37

2023-04-07 08:45 UTC, 5tr1ker commented on src/main/java/com/team/comma/config/WebConfig.java
> +
Spring Security 파일 내부에서 cors 허용할 수 있지만 따로 다른 파일로 빼서 설정한 이유가 있을까요?

https://toycoms.tistory.com/37

2023-04-07 08:45 UTC, 5tr1ker commented on src/main/java/com/team/comma/dto/RegisterRequest.java
> +	private String recommendTime;
LocalDateTime 클래스를 활용하면 날짜 연산과 비교도 쉽고 JSON으로도 변환이 가능한데 String으로 설정한 이유가 무엇인가요?

2023-04-07 08:51 UTC, wan2daaa commented on src/main/java/com/team/comma/dto/RegisterRequest.java
> +	private String recommendTime;
그 메인 브랜치 Swagger 상에서 recommendTime 부분의 예시랑 설명 부분이 안나와서
String으로 변경하니 정상 작동이되어서 일단 임시로 바꿔두었습니다!
이 부분설명을 안적어놓아서  따로 FIXME 주석 달아 놓겠습니다! :>
https://sowon-dev.github.io/2021/05/12/210513Eclipse-tasks/

2023-04-07 08:51 UTC, wan2daaa commented on src/main/java/com/team/comma/config/WebConfig.java
> +
잘 모르는 부분이여가지구,,
감사합니다 보고 수정하겠습니다 !

2023-04-07 08:58 UTC, given02 commented on src/main/java/com/team/comma/dto/RegisterRequest.java
> +	private String recommendTime;
recommandtime으로 연산과 비교 하는 상황이 어떻게 될까요??
recommandtime에는 연월일은 필요가 없는데 localdatetime을 쓰면 연월일에 임의의 값을 넣어야해서 판단이 필요할 것 같습니다.

2023-04-07 09:02 UTC, given02 approved these changes
recommnadtime을 포함 한 entity 관련 내용은 회의 후 수정하면 될 것 같습니다.

2023-04-07 13:48 UTC, ahhyunyoon approved these changes

2023-04-09 11:29 UTC, 5tr1ker approved these changes

2023-04-10 02:41 UTC, merged