Feature: 프로필 페이지 좋아요 표시한 트랙 리스트 조회 기능 구현
CommaProject/Comma-Back-end pull request #94
Opened 2023-08-24 06:29 UTC by given02

<h2>Jira Issue 번호</h2>

121

<h2>작업 내용</h2>

- 좋아요 표시한 트랙 리스트 조회 기능 구현
- restDocs 일부 수정
- Track 에서 Favorite Track 분리 작업

<h2>Check-List</h2>

- [x] PR 제목이 convention 에 맞는지 체크
- [x] PR Label 설정
- [x] Code Review 요청
- [x] Jira 리뷰 요청 상태로 변경

2023-08-26 14:58 UTC, 5tr1ker requested changes

2023-08-26 14:58 UTC, 5tr1ker commented on src/main/java/com/team/comma/domain/favorite/track/dto/FavoriteTrackRequest.java
> +}
혹시 사용하지 않는다면 제거하는건 어떠신가용

2023-08-26 14:58 UTC, 5tr1ker commented on src/main/java/com/team/comma/domain/favorite/track/service/FavoriteTrackService.java
> +        FavoriteTrack result = FavoriteTrack.buildFavoriteTrack(user , trackService.findTrackOrElseSave(trackRequest.getSpotifyTrackId()));
Or ( 또는 ) Else ( 또 다른 ) 가 같은 의미인데 하나만 사용하셔도 될꺼같아요!

2023-08-26 14:58 UTC, 5tr1ker commented on src/main/java/com/team/comma/domain/favorite/track/service/FavoriteTrackService.java
> +        List<FavoriteTrack> favoriteTracks = findAllByUser(user);
단순 findAll 은 목적어가 없어서 보기 힘든데 FavoriteTrack 추가하는건 어떤가요

2023-08-26 14:58 UTC, 5tr1ker commented on src/main/java/com/team/comma/domain/favorite/track/service/FavoriteTrackService.java
> +        }
이렇게 하나하나 넣는것 보단 쿼리에서 join 문을 이용해서 모두 가져오는건 어떤가요? 시간 복잡도는 2배 가까이 줄어들거 같아요

2023-08-26 14:58 UTC, 5tr1ker commented
단일 책임의 메서드는 잘 만드셨는데 이제 로직상 최적화만 잘 된다면 좋을 꺼 같아요!

2023-08-26 23:16 UTC, given02 commented on src/main/java/com/team/comma/domain/favorite/track/service/FavoriteTrackService.java
> +        FavoriteTrack result = FavoriteTrack.buildFavoriteTrack(user , trackService.findTrackOrElseSave(trackRequest.getSpotifyTrackId()));
원래 있던 거 갖다 쓴거라ㅠ 그럼 관련해서 모두 수정할게요

2023-08-27 11:38 UTC, 5tr1ker approved these changes
고생하셨습니다!

2023-08-27 12:16 UTC, merged