Feature: 좋아요 표시한 아티스트 리스트 조회 API 구현
CommaProject/Comma-Back-end pull request #95
Opened 2023-08-25 11:40 UTC by given02

<h2>Jira Issue 번호</h2>

122

<h2>작업 내용</h2>

- 좋아요 표시한 아티스트 리스트 조회
- spotify 검색 시 history 추가 되는 로직 제거

<h2>Check-List</h2>

- [x] PR 제목이 convention 에 맞는지 체크
- [x] PR Label 설정
- [x] Code Review 요청
- [x] Jira 리뷰 요청 상태로 변경

2023-08-26 15:16 UTC, 5tr1ker requested changes
이전 PR 이랑 겹치는게 있어서 그거 제외하고 했습니다!

2023-08-26 15:16 UTC, 5tr1ker commented on src/main/java/com/team/comma/domain/favorite/artist/repository/FavoriteArtistRepository.java
> +    List<FavoriteArtist> findAllByUser(User user);
목적어가 없어서 단순히 "유저로 모두 찾는다" 가 되는데 "유저로 모든 최애 가수를 찾는다" 로 읽히게 FavoriteArtist 를 넣는건 어떤가요

2023-08-26 15:16 UTC, 5tr1ker commented on src/main/java/com/team/comma/domain/favorite/artist/service/FavoriteArtistService.java
> +        }
여기도 각각 add 하기 때문에 N * 2 의 시간 복잡도가 발생하는데 차라리 join 을 이용해서 한번에 조회를 한다면 5줄의 코드를 한 줄로 줄일 수 있을 꺼 같아요!

2023-08-26 15:16 UTC, 5tr1ker commented on src/main/java/com/team/comma/domain/favorite/artist/service/FavoriteArtistService.java
> +    }
여기도 메서드 명이 어려워용

2023-08-26 15:16 UTC, 5tr1ker commented on src/main/java/com/team/comma/domain/favorite/track/dto/FavoriteTrackRequest.java
> +}
사용하지 않는 파일인거 같습니당

2023-08-26 15:16 UTC, 5tr1ker commented on src/main/java/com/team/comma/domain/favorite/track/dto/FavoriteTrackResponse.java
> +}
만약에 이렇게 모든 Id 를 가져온다면 DB 쿼리를 사용하는건 어떠신가요

2023-08-27 14:37 UTC, 5tr1ker requested changes

2023-08-27 14:37 UTC, 5tr1ker commented on src/main/java/com/team/comma/domain/favorite/artist/controller/FavoriteArtistController.java
> +                .body(favoriteArtistService.findALlFavoriteArtist(accessToken));
요기 메서드 명이 이상한 거 같습니다.

2023-08-27 14:37 UTC, 5tr1ker commented on src/main/java/com/team/comma/domain/user/following/controller/FollowingController.java
브라우저에 따라 GET 에 BODY 데이터가 담기지 않은 브라우저가 많고 , 데이터를 담는걸 추천하지 않더라구요! 파라미터를 이용하거나 POST 를 이용하는건 어떠신가요

2023-08-27 14:47 UTC, given02 commented on src/main/java/com/team/comma/domain/user/following/controller/FollowingController.java
안그래도 다른거 하나는 고쳤는데 이런게 더 있는 거 같아 리팩토링 할 때 수정 해야할 듯

2023-08-27 16:45 UTC, 5tr1ker approved these changes
고생하셨습니다!

2023-08-27 16:48 UTC, merged